[package]
name = "rustverb"
version = "0.1.0"
authors = ["Richard Mitic <richard.h.mitic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
hound = "3.4.0"
time_calc = "0.13.0"
